java_plugin(
    name = "lombok_plugin",
    generates_api = True,
    processor_class = "lombok.launch.AnnotationProcessorHider$AnnotationProcessor",
    visibility = ["//visibility:public"],
    deps = ["@maven//:org_projectlombok_lombok_1_18_26"],
)

java_library(
    name = "lombok",
    exported_plugins = [":lombok_plugin"],
)

java_library(
    name = "todo-microservice-lib",
    srcs = glob(["src/main/java/com/incode/todo/**/*.java"]),
    resources = [
        "src/main/resources/application.yaml",
        "src/main/resources/db/migration/v1_initialize/v1.1_create_roles.sql",
        "src/main/resources/db/migration/v1_initialize/v1.2_create_schema.sql",
        "src/main/resources/db/migration/v1_initialize/v1.3_create_reference_data.sql",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":lombok",
        "@maven//:ch_qos_logback_logback_classic_1_4_5",
        "@maven//:ch_qos_logback_logback_core_1_4_5",
        "@maven//:com_fasterxml_classmate_1_5_1",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations_2_14_1",
        "@maven//:com_fasterxml_jackson_core_jackson_core_2_14_1",
        "@maven//:com_fasterxml_jackson_core_jackson_databind_2_14_1",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8_2_14_1",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310_2_14_1",
        "@maven//:com_fasterxml_jackson_module_jackson_module_parameter_names_2_14_1",
        "@maven//:com_jayway_jsonpath_json_path_2_7_0",
        "@maven//:com_ongres_scram_client_2_1",
        "@maven//:com_ongres_scram_common_2_1",
        "@maven//:com_ongres_stringprep_saslprep_1_1",
        "@maven//:com_ongres_stringprep_stringprep_1_1",
        "@maven//:com_vaadin_external_google_android_json_0_0_20131108_vaadin1",
        "@maven//:commons_codec_commons_codec_1_15",
        "@maven//:io_micrometer_micrometer_commons_1_10_2",
        "@maven//:io_micrometer_micrometer_core_1_10_2",
        "@maven//:io_micrometer_micrometer_observation_1_10_2",
        "@maven//:io_netty_incubator_netty_incubator_codec_classes_quic_0_0_33_Final",
        "@maven//:io_netty_incubator_netty_incubator_codec_native_quic_0_0_33_Final",
        "@maven//:io_netty_netty_buffer_4_1_85_Final",
        "@maven//:io_netty_netty_codec_4_1_85_Final",
        "@maven//:io_netty_netty_codec_dns_4_1_85_Final",
        "@maven//:io_netty_netty_codec_http2_4_1_85_Final",
        "@maven//:io_netty_netty_codec_http_4_1_85_Final",
        "@maven//:io_netty_netty_codec_socks_4_1_85_Final",
        "@maven//:io_netty_netty_common_4_1_85_Final",
        "@maven//:io_netty_netty_handler_4_1_85_Final",
        "@maven//:io_netty_netty_handler_proxy_4_1_85_Final",
        "@maven//:io_netty_netty_resolver_4_1_85_Final",
        "@maven//:io_netty_netty_resolver_dns_4_1_85_Final",
        "@maven//:io_netty_netty_resolver_dns_classes_macos_4_1_85_Final",
        "@maven//:io_netty_netty_resolver_dns_native_macos_4_1_85_Final",
        "@maven//:io_netty_netty_transport_4_1_85_Final",
        "@maven//:io_netty_netty_transport_classes_epoll_4_1_85_Final",
        "@maven//:io_netty_netty_transport_native_epoll_4_1_85_Final",
        "@maven//:io_netty_netty_transport_native_unix_common_4_1_85_Final",
        "@maven//:io_projectreactor_addons_reactor_pool_1_0_0",
        "@maven//:io_projectreactor_netty_incubator_reactor_netty_incubator_quic_0_1_0",
        "@maven//:io_projectreactor_netty_reactor_netty_1_1_0",
        "@maven//:io_projectreactor_netty_reactor_netty_core_1_1_0",
        "@maven//:io_projectreactor_netty_reactor_netty_http_1_1_0",
        "@maven//:io_projectreactor_reactor_core_3_5_0",
        "@maven//:io_projectreactor_reactor_test_3_5_0",
        "@maven//:io_r2dbc_r2dbc_pool_1_0_0_RELEASE",
        "@maven//:io_r2dbc_r2dbc_postgresql_0_8_13_RELEASE",
        "@maven//:io_r2dbc_r2dbc_spi_1_0_0_RELEASE",
        "@maven//:jakarta_activation_jakarta_activation_api_2_1_0",
        "@maven//:jakarta_annotation_jakarta_annotation_api_2_1_1",
        "@maven//:jakarta_validation_jakarta_validation_api_3_0_2",
        "@maven//:jakarta_xml_bind_jakarta_xml_bind_api_4_0_0",
        "@maven//:net_bytebuddy_byte_buddy_1_12_19",
        "@maven//:net_bytebuddy_byte_buddy_agent_1_12_19",
        "@maven//:net_minidev_accessors_smart_2_4_8",
        "@maven//:net_minidev_json_smart_2_4_8",
        "@maven//:org_apache_logging_log4j_log4j_api_2_19_0",
        "@maven//:org_apache_logging_log4j_log4j_to_slf4j_2_19_0",
        "@maven//:org_apache_tomcat_embed_tomcat_embed_el_10_1_1",
        "@maven//:org_apiguardian_apiguardian_api_1_1_2",
        "@maven//:org_assertj_assertj_core_3_23_1",
        "@maven//:org_hamcrest_hamcrest_2_2",
        "@maven//:org_hdrhistogram_HdrHistogram_2_1_12",
        "@maven//:org_hibernate_validator_hibernate_validator_8_0_0_Final",
        "@maven//:org_jboss_logging_jboss_logging_3_5_0_Final",
        "@maven//:org_junit_jupiter_junit_jupiter_5_9_1",
        "@maven//:org_junit_jupiter_junit_jupiter_api_5_9_1",
        "@maven//:org_junit_jupiter_junit_jupiter_engine_5_9_1",
        "@maven//:org_junit_jupiter_junit_jupiter_params_5_9_1",
        "@maven//:org_junit_platform_junit_platform_commons_1_9_1",
        "@maven//:org_junit_platform_junit_platform_engine_1_9_1",
        "@maven//:org_latencyutils_LatencyUtils_2_0_3",
        "@maven//:org_mockito_mockito_core_4_8_1",
        "@maven//:org_mockito_mockito_junit_jupiter_4_8_1",
        "@maven//:org_objenesis_objenesis_3_2",
        "@maven//:org_opentest4j_opentest4j_1_2_0",
        "@maven//:org_ow2_asm_asm_9_1",
        "@maven//:org_projectlombok_lombok_1_18_26",
        "@maven//:org_reactivestreams_reactive_streams_1_0_4",
        "@maven//:org_skyscreamer_jsonassert_1_5_1",
        "@maven//:org_slf4j_jul_to_slf4j_2_0_4",
        "@maven//:org_slf4j_slf4j_api_2_0_4",
        "@maven//:org_springframework_boot_spring_boot_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_actuator_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_actuator_autoconfigure_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_devtools_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_actuator_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_data_r2dbc_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_json_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_logging_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_reactor_netty_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_test_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_validation_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_starter_web_3_0_0",
        # "@maven//:org_springframework_boot_spring_boot_starter_webflux_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_test_3_0_0",
        "@maven//:org_springframework_boot_spring_boot_test_autoconfigure_3_0_0",
        "@maven//:org_springframework_data_spring_data_commons_3_0_0",
        "@maven//:org_springframework_data_spring_data_r2dbc_3_0_0",
        "@maven//:org_springframework_data_spring_data_relational_3_0_0",
        "@maven//:org_springframework_spring_aop_6_0_2",
        "@maven//:org_springframework_spring_beans_6_0_2",
        "@maven//:org_springframework_spring_context_6_0_2",
        "@maven//:org_springframework_spring_core_6_0_2",
        "@maven//:org_springframework_spring_expression_6_0_2",
        "@maven//:org_springframework_spring_jcl_6_0_2",
        "@maven//:org_springframework_spring_jdbc_6_0_2",
        "@maven//:org_springframework_spring_r2dbc_6_0_2",
        "@maven//:org_springframework_spring_test_6_0_2",
        "@maven//:org_springframework_spring_tx_6_0_2",
        "@maven//:org_springframework_spring_web_6_0_2",
        "@maven//:org_springframework_spring_webflux_6_0_2",
        "@maven//:org_xmlunit_xmlunit_core_2_9_0",
        "@maven//:org_yaml_snakeyaml_1_33",
    ],
)

java_test(
    name = "todo-microservice-test",
    size = "small",
    srcs = ["src/test/java/com/incode/todo/ApplicationTests.java"],
    resources = [
    ],
    test_class = "com.incode.todo.ApplicationTests",
    deps = [
        ":todo-microservice-lib",
    ],
)

java_binary(
    name = "todo-microservice",
    main_class = "com.incode.todo.Application",
    runtime_deps = [
        ":todo-microservice-lib",
    ],
)
