GET /api/v1/tasks HTTP/1.1
Host: localhost:8080

###
POST /api/v1/tasks HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "title": "Custom title",
    "description": "This is my custom description"
}

###
GET /api/v1/tasks/846cba17-06da-4c63-9d61-23f729f75f13 HTTP/1.1
Host: localhost:8080

### 
PATCH /api/v1/tasks/846cba17-06da-4c63-9d61-23f729f75f13?completed=true HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "title": "Updated title",
    "description": "Updated description"
}

###
DELETE /api/v1/tasks/846cba17-06da-4c63-9d61-23f729f75f13?soft=false HTTP/1.1
Host: localhost:8080

###
GET /admin/liveness HTTP/1.1
Host: localhost:8084

###
GET /admin/readiness HTTP/1.1
Host: localhost:8084
