spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 1
      max-size: 2
      max-idle-time: 30m

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    default-schema: todo
    schemas: 
    - todo
    locations:
    - classpath:db/migration
    sqlMigrationPrefix: v
    repeatableSqlMigrationPrefix: x
    sqlMigrationSeparator: _
    table: schema_version
    group: true
    mixed: true

server:
  port: 8080

management:
  server:
    port: 8084
    address: 0.0.0.0
    ssl:
      enabled: false
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "*"
      base-path: "/admin"
      path-mapping:
        health: "/readiness"
        info: "/liveness"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    diskspace:
      enabled: false