spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 16
      max-idle-time: 30m

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    default-schema: todo
    schemas: 
    - todo
    locations:
    - classpath:db/migration
    sqlMigrationPrefix: v
    repeatableSqlMigrationPrefix: x
    sqlMigrationSeparator: _
    table: schema_version
    group: true
    mixed: true