spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=todo
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 1
      max-size: 2
      max-idle-time: 30m

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

server:
  port: 8080

management:
  server:
    port: 8084
    address: 0.0.0.0
    ssl:
      enabled: false
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "*"
      base-path: "/admin"
      path-mapping:
        health: "/readiness"
        info: "/liveness"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

  jackson:
    default-property-inclusion: non_null

  #jackson:serialization-inclusion=non_null

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    com.incode.todo: DEBUG
